export const preguntasIniciales = [
  {
    id: 1,
    texto: '',
    palabra: "Cheat",
    opciones: [
      "Engañar/Hacer trampa", 
      "Defraudar", 
      "Mentir", 
      "Estafar", 
      "Trampear", 
      "Timar",
    ],
    respuestasCorrectas: ["Engañar/Hacer trampa"],
    fonetica: ["ʧit"],
  },
  {
    id: 2,
    texto: '',
    palabra: "Check",
    opciones: [
      "Comprobar", 
      "Verificar", 
      "Revisar", 
      "Inspeccionar", 
      "Examinar", 
      "Analizar",
    ],
    respuestasCorrectas: ["Comprobar"],
    fonetica: ["ʧɛk"],
  },
  {
    id: 3,
    texto: '',
    palabra: "Clap",
    opciones: [
      "Aplaudir", 
      "Palmotear", 
      "Golpear las manos", 
      "Aclamarse", 
      "Festejar", 
      "Vitorear",
    ],
    respuestasCorrectas: ["Aplaudir"],
    fonetica: ["klæp"],
  },
  {
    id: 4,
    texto: '',
    palabra: "Clean",
    opciones: [
      "Limpiar", 
      "Desinfectar", 
      "Pulir", 
      "Lavar", 
      "Asear", 
      "Higienizar",
    ],
    respuestasCorrectas: ["Limpiar"],
    fonetica: ["klin"],
  },
  {
    id: 5,
    texto: '',
    palabra: "Close",
    opciones: [
      "Cerrar", 
      "Clausurar", 
      "Serrar", 
      "Sellar", 
      "Bloquear", 
      "Encerrar",
    ],
    respuestasCorrectas: ["Cerrar"],
    fonetica: ["kloʊs"],
  },
  {
    id: 6,
    texto: '',
    palabra: "Comb",
    opciones: [
      "Peinar", 
      "Cepillar", 
      "Desenredar", 
      "Alisar", 
      "Pasar el peine", 
      "Acomodar",
    ],
    respuestasCorrectas: ["Peinar"],
    fonetica: ["Comb"],
  },
  {
    id: 7,
    texto: '',
    palabra: "Commit",
    opciones: [
      "Cometer", 
      "Realizar", 
      "Ejecutar", 
      "Perpetrar", 
      "Llevar a cabo", 
      "Cumplir",
    ],
    respuestasCorrectas: ["Cometer"],
    fonetica: ["kəˈmɪt"],
  },
  {
    id: 8,
    texto: '',
    palabra: "Compare",
    opciones: [
      "Comparar", 
      "Contrastar", 
      "Evaluar", 
      "Analizar", 
      "Medir", 
      "Examinar",
    ],
    respuestasCorrectas: ["Comparar"],
    fonetica: ["kəmˈpɛr"],
  },
  {
    id: 9,
    texto: '',
    palabra: "Connect",
    opciones: [
      "Conectar", 
      "Enlazar", 
      "Vincular", 
      "Unir", 
      "Acoplar", 
      "Relacionar",
    ],
    respuestasCorrectas: ["Conectar"],
    fonetica: ["kəˈnɛkt"],
  },
  {
    id: 10,
    texto: '',
    palabra: "Consider",
    opciones: [
      "Considerar", 
      "Reflexionar", 
      "Pensar", 
      "Meditar", 
      "Evaluar", 
      "Tener en cuenta",
    ],
    respuestasCorrectas: ["Considerar"],
    fonetica: ["kənˈsɪdər"],
  },
  {
    id: 11,
    texto: '',
    palabra: "Contain",
    opciones: [
      "Contener", 
      "Incluir", 
      "Abarcar", 
      "Encerrar", 
      "Sostener", 
      "Cercar",
    ],
    respuestasCorrectas: ["Contener"],
    fonetica: ["kənˈteɪn"],
  },
  {
    id: 12,
    texto: '',
    palabra: "Continue",
    opciones: [
      "Continuar", 
      "Seguir", 
      "Proseguir", 
      "Persistir", 
      "Reanudar", 
      "Mantener",
    ],
    respuestasCorrectas: ["Continuar"],
    fonetica: ["kənˈtɪnju"],
  },
  {
    id: 13,
    texto: '',
    palabra: "Control",
    opciones: [
      "Controlar", 
      "Dominar", 
      "Supervisar", 
      "Regular", 
      "Monitorizar", 
      "Gestionar",
    ],
    respuestasCorrectas: ["Controlar"],
    fonetica: ["kənˈtroʊl"],
  },
  {
    id: 14,
    texto: '',
    palabra: "Cook",
    opciones: [
      "Cocinar", 
      "Guisar", 
      "Freír", 
      "Asar", 
      "Hervir", 
      "Preparar",
    ],
    respuestasCorrectas: ["Cocinar"],
    fonetica: ["kʊk"],
  },
  {
    id: 15,
    texto: '',
    palabra: "Crash",
    opciones: [
      "Chocar", 
      "Colisionar", 
      "Accidentarse", 
      "Estrellarse", 
      "Impactar", 
      "Desplomarse",
    ],
    respuestasCorrectas: ["Chocar"],
    fonetica: ["kræʃ"],
  },
  {
    id: 16,
    texto: '',
    palabra: "Create",
    opciones: [
      "Crear", 
      "Generar", 
      "Producir", 
      "Formar", 
      "Diseñar", 
      "Inventar",
    ],
    respuestasCorrectas: ["Crear"],
    fonetica: ["kriˈeɪt"],
  },
  {
    id: 17,
    texto: '',
    palabra: "Cry",
    opciones: [
      "Llorar", 
      "Sollozar", 
      "Gimotear", 
      "Lagrimear", 
      "Berrear", 
      "Gemir",
    ],
    respuestasCorrectas: ["Llorar"],
    fonetica: ["kraɪ"],
  },
  {
    id: 18,
    texto: '',
    palabra: "Dance",
    opciones: [
      "Bailar", 
      "Danzar", 
      "Moverse", 
      "Saltar", 
      "Valsear", 
      "Zambullirse",
    ],
    respuestasCorrectas: ["Bailar"],
    fonetica: ["dæns"],
  },
  {
    id: 19,
    texto: '',
    palabra: "Dare",
    opciones: [
      "Atreverse", 
      "Desafiar", 
      "Retar", 
      "Osar", 
      "Provocar", 
      "Emprender",
    ],
    respuestasCorrectas: ["Atreverse"],
    fonetica: ["dɛr"],
  },
  {
    id: 20,
    texto: '',
    palabra: "Decide",
    opciones: [
      "Decidir", 
      "Elegir", 
      "Resolver", 
      "Determinar", 
      "Optar", 
      "Seleccionar",
    ],
    respuestasCorrectas: ["Decidir"],
    fonetica: ["ˌdɪˈsaɪd"],
  },
];