//module stream
export const preguntasIniciales = [
  {
    id: 1,
    texto: "",
    palabra: "stream.Readable",
    opciones: [
      "Base for readable streams.",
      "Base for writable streams.",
      "Allows both reading and writing simultaneously.",
      "Transforms data as it is read.",
      "Handles stream errors.",
      "Closes the stream after data is processed.",
    ],
    respuestasCorrectas: ["Base for readable streams."],
  },
  {
    id: 2,
    texto: "",
    word: "stream.Writable",
    opciones: [
      "Base for writable streams.",
      "Base for readable streams.",
      "Allows both reading and writing simultaneously.",
      "Transforms data as it is written.",
      "Handles stream errors.",
      "Closes the stream after data is written.",
    ],
    respuestasCorrectas: ["Base for writable streams."],
  },
  {
    id: 3,
    texto: "",
    word: "stream.Duplex",
    opciones: [
      "Allows both reading and writing simultaneously.",
      "Base for writable streams.",
      "Base for readable streams.",
      "Transforms data as it is read or written.",
      "Handles stream errors.",
      "Closes the stream after data is processed.",
    ],
    respuestasCorrectas: ["Allows both reading and writing simultaneously."],
  },
  {
    id: 4,
    texto: "",
    word: "stream.Transform",
    opciones: [
      "Similar to Duplex, but with data transformation.",
      "Base for writable streams.",
      "Base for readable streams.",
      "Handles stream errors.",
      "Closes the stream after data is processed.",
      "Allows both reading and writing simultaneously.",
    ],
    respuestasCorrectas: ["Similar to Duplex, but with data transformation."],
  },
  {
    id: 5,
    texto: "",
    word: "stream.pipe()",
    opciones: [
      "Connects readable streams to writable streams easily.",
      "Triggers when new data is available in the stream.",
      "Ends the stream and sends the last data.",
      "Handles stream errors.",
      "Transforms data while reading or writing.",
      "Closes the writable stream after writing data.",
    ],
    respuestasCorrectas: ["Connects readable streams to writable streams easily."],
  },
  {
    id: 6,
    texto: "",
    word: "stream.on('data', callback)",
    opciones: [
      "Triggers when new data is available.",
      "Ends the stream when data is finished.",
      "Handles errors in the stream.",
      "Writes data to the stream.",
      "Transforms data as it flows through the stream.",
      "Closes the stream after writing data.",
    ],
    respuestasCorrectas: ["Triggers when new data is available."],
  },
  {
    id: 7,
    texto: "",
    word: "stream.on('end', callback)",
    opciones: [
      "Emitted when all data in the stream has been processed.",
      "Triggers when new data is available in the stream.",
      "Handles errors in the stream.",
      "Writes data to the stream.",
      "Transforms data during the reading process.",
      "Closes the writable stream after data is written.",
    ],
    respuestasCorrectas: ["Emitted when all data in the stream has been processed."],
  },
  {
    id: 8,
    texto: "",
    word: "stream.on('error', callback)",
    opciones: [
      "Catches errors in the data flow.",
      "Triggers when new data is available.",
      "Ends the stream and sends the last data.",
      "Connects readable streams to writable streams.",
      "Writes data to the stream.",
      "Transforms data during reading or writing.",
    ],
    respuestasCorrectas: ["Catches errors in the data flow."],
  },
  {
    id: 9,
    texto: "",
    word: "stream.write()",
    opciones: [
      "Writes data to a writable stream.",
      "Triggers when new data is available in the stream.",
      "Ends the stream and sends the last data.",
      "Handles errors in the stream.",
      "Transforms data while being written.",
      "Closes the stream after writing data.",
    ],
    respuestasCorrectas: ["Writes data to a writable stream."],
  },
  {
    id: 10,
    texto: "",
    word: "stream.end()",
    opciones: [
      "Ends the stream and sends the last data.",
      "Triggers when new data is available in the stream.",
      "Catches errors in the data flow.",
      "Writes data to the stream.",
      "Transforms data as it is processed.",
      "Closes the stream after data is written.",
    ],
    respuestasCorrectas: ["Ends the stream and sends the last data."],
  },
];
