export const preguntasIniciales = [
  {
    id: 1,
    texto: '',
    palabra: "Get",
    opciones: [
      "Conseguir/Obtener", 
      "Adquirir", 
      "Lograr", 
      "Recibir", 
      "Captar", 
      "Alcanzar",
    ],
    respuestasCorrectas: ["Conseguir/Obtener"],
    fonetica: ["ɡɛt"],
  },
  {
    id: 2,
    texto: '',
    palabra: "Give",
    opciones: [
      "Dar", 
      "Entregar", 
      "Ofrecer", 
      "Proveer", 
      "Conceder", 
      "Donar",
    ],
    respuestasCorrectas: ["Dar"],
    fonetica: ["ɡɪv"],
  },
  {
    id: 3,
    texto: '',
    palabra: "Go",
    opciones: [
      "Ir", 
      "Partir", 
      "Dirigirse", 
      "Trasladarse", 
      "Moverse", 
      "Marcharse",
    ],
    respuestasCorrectas: ["Ir"],
    fonetica: ["ɡoʊ"],
  },
  {
    id: 4,
    texto: '',
    palabra: "Grind",
    opciones: [
      "Moler", 
      "Triturar", 
      "Pulverizar", 
      "Machacar", 
      "Desmenuzar", 
      "Reducir a polvo",
    ],
    respuestasCorrectas: ["Moler"],
    fonetica: ["ɡraɪnd"],
  },
  {
    id: 5,
    texto: '',
    palabra: "Grow",
    opciones: [
      "Crecer", 
      "Desarrollarse", 
      "Incrementar", 
      "Expandirse", 
      "Aumentar", 
      "Ampliarse",
    ],
    respuestasCorrectas: ["Crecer"],
    fonetica: ["ɡroʊ"],
  },
  {
    id: 6,
    texto: '',
    palabra: "Hang",
    opciones: [
      "Colgar", 
      "Suspender", 
      "Tender", 
      "Sujetar", 
      "Anclar", 
      "Fijar",
    ],
    respuestasCorrectas: ["Colgar"],
    fonetica: ["hæŋ"],
  },
  {
    id: 7,
    texto: '',
    palabra: "Have",
    opciones: [
      "Tener", 
      "Poseer", 
      "Disponer", 
      "Contar con", 
      "Mantener", 
      "Sostener",
    ],
    respuestasCorrectas: ["Tener"],
    fonetica: ["hæv"],
  },
  {
    id: 8,
    texto: '',
    palabra: "Hear",
    opciones: [
      "Oír", 
      "Escuchar", 
      "Percibir", 
      "Captar", 
      "Atender", 
      "Detectar",
    ],
    respuestasCorrectas: ["Oír"],
    fonetica: ["hir"],
  },
  {
    id: 9,
    texto: '',
    palabra: "Hide",
    opciones: [
      "Esconder/Ocultar", 
      "Encubrir", 
      "Disimular", 
      "Enmascarar", 
      "Guardar", 
      "Velar",
    ],
    respuestasCorrectas: ["Esconder/Ocultar"],
    fonetica: ["haɪd"],
  },
  {
    id: 10,
    texto: '',
    palabra: "Hit",
    opciones: [
      "Golpear", 
      "Pegar", 
      "Chocar", 
      "Impactar", 
      "Dar un golpe", 
      "Acometer",
    ],
    respuestasCorrectas: ["Golpear"],
    fonetica: ["hɪt"],
  },
  {
    id: 11,
    texto: '',
    palabra: "Hold",
    opciones: [
      "Sostener/Agarrar", 
      "Sujetar", 
      "Mantener", 
      "Contener", 
      "Abrazar", 
      "Agarrar fuertemente",
    ],
    respuestasCorrectas: ["Sostener/Agarrar"],
    fonetica: ["hoʊld"],
  },
  {
    id: 12,
    texto: '',
    palabra: "Hurt",
    opciones: [
      "Lastimar", 
      "Dañar", 
      "Herir", 
      "Lesionar", 
      "Afligir", 
      "Causar dolor",
    ],
    respuestasCorrectas: ["Lastimar"],
    fonetica: ["hɜrt"],
  },
  {
    id: 13,
    texto: '',
    palabra: "Keep",
    opciones: [
      "Guardar/Cumplir", 
      "Mantener", 
      "Conservar", 
      "Preservar", 
      "Retener", 
      "Sostener",
    ],
    respuestasCorrectas: ["Guardar/Cumplir"],
    fonetica: ["kip"],
  },
  {
    id: 14,
    texto: '',
    palabra: "Kneel",
    opciones: [
      "Arrodillarse", 
      "Inclinarse", 
      "Postrarse", 
      "Doblar la rodilla", 
      "Genuflexionar", 
      "Poner la rodilla en tierra",
    ],
    respuestasCorrectas: ["Arrodillarse"],
    fonetica: ["nil"],
  },
  {
    id: 15,
    texto: '',
    palabra: "Know",
    opciones: [
      "Saber", 
      "Conocer", 
      "Entender", 
      "Comprender", 
      "Percibir", 
      "Reconocer",
    ],
    respuestasCorrectas: ["Saber"],
    fonetica: ["noʊ"],
  },
  {
    id: 16,
    texto: '',
    palabra: "Lead",
    opciones: [
      "Llevar", 
      "Guiar", 
      "Conducir", 
      "Dirigir", 
      "Encabezar", 
      "Pilotar",
    ],
    respuestasCorrectas: ["Llevar"],
    fonetica: ["lid"],
  },
  {
    id: 17,
    texto: '',
    palabra: "Leave",
    opciones: [
      "Dejar", 
      "Abandonar", 
      "Salir", 
      "Partir", 
      "Irse", 
      "Desistir",
    ],
    respuestasCorrectas: ["Dejar"],
    fonetica: ["liv"],
  },
  {
    id: 18,
    texto: '',
    palabra: "Lend",
    opciones: [
      "Prestar", 
      "Rentar", 
      "Dar en préstamo", 
      "Facilitar", 
      "Proveer", 
      "Alquilar",
    ],
    respuestasCorrectas: ["Prestar"],
    fonetica: ["lɛnd"],
  },
  {
    id: 19,
    texto: '',
    palabra: "Let",
    opciones: [
      "Permitir", 
      "Autorizar", 
      "Dejar", 
      "Consentir", 
      "Conceder", 
      "Facultar",
    ],
    respuestasCorrectas: ["Permitir"],
    fonetica: ["lɛt"],
  },
  {
    id: 20,
    texto: '',
    palabra: "Lose",
    opciones: [
      "Perder", 
      "Extraviar", 
      "Despojarse de", 
      "Olvidar", 
      "Desvanecer", 
      "Dilapidar",
    ],
    respuestasCorrectas: ["Perder"],
    fonetica: ["luz"],
  },
];