export const preguntasIniciales = [
  {
    id: 1,
    texto: '',
    palabra: "Heart",
    opciones: [
      "Corazón", 
      "Cerebro", 
      "Estómago", 
      "Hígado", 
      "Pulmón", 
      "Riñón",
    ],
    respuestasCorrectas: ["Corazón"],
    fonetica: ["hɑrt"],
  },
  {
    id: 2,
    texto: '',
    palabra: "Lung",
    opciones: [
      "Pulmón", 
      "Corazón", 
      "Hígado", 
      "Riñón", 
      "Estómago", 
      "Intestino",
    ],
    respuestasCorrectas: ["Pulmón"],
    fonetica: ["lʌŋ"],
  },
  {
    id: 3,
    texto: '',
    palabra: "Stomach",
    opciones: [
      "Estómago", 
      "Intestinos", 
      "Riñón", 
      "Hígado", 
      "Corazón", 
      "Pulmón",
    ],
    respuestasCorrectas: ["Estómago"],
    fonetica: ["ˈstʌmək"],
  },
  {
    id: 4,
    texto: '',
    palabra: "Intestines",
    opciones: [
      "Intestinos", 
      "Estómago", 
      "Riñón", 
      "Hígado", 
      "Pulmón", 
      "Corazón",
    ],
    respuestasCorrectas: ["Intestinos"],
    fonetica: ["ɪnˈtɛstənz"],
  },
  {
    id: 5,
    texto: '',
    palabra: "Liver",
    opciones: [
      "Hígado", 
      "Riñón", 
      "Estómago", 
      "Intestinos", 
      "Corazón", 
      "Pulmón",
    ],
    respuestasCorrectas: ["Hígado"],
    fonetica: ["ˈlɪvər"],
  },
  {
    id: 6,
    texto: '',
    palabra: "Kidney",
    opciones: [
      "Riñón", 
      "Hígado", 
      "Intestinos", 
      "Estómago", 
      "Corazón", 
      "Pulmón",
    ],
    respuestasCorrectas: ["Riñón"],
    fonetica: ["ˈkɪdni"],
  },
  {
    id: 7,
    texto: '',
    palabra: "Vein",
    opciones: [
      "Vena", 
      "Arteria", 
      "Capilar", 
      "Válvula", 
      "Ventrículo", 
      "Aurícula",
    ],
    respuestasCorrectas: ["Vena"],
    fonetica: ["veɪn"],
  },
  {
    id: 8,
    texto: '',
    palabra: "Artery",
    opciones: [
      "Arteria", 
      "Vena", 
      "Tendón", 
      "Ligamento", 
      "Cartílago", 
      "Músculo",
    ],
    respuestasCorrectas: ["Arteria"],
    fonetica: ["ˈɑrtəri"],
  },
  {
    id: 9,
    texto: '',
    palabra: "Tendon",
    opciones: [
      "Tendón", 
      "Músculo", 
      "Ligamento", 
      "Cartílago", 
      "Arteria", 
      "Vena",
    ],
    respuestasCorrectas: ["Tendón"],
    fonetica: ["ˈtɛndən"],
  },
  {
    id: 10,
    texto: '',
    palabra: "Muscle",
    opciones: [
      "Músculo", 
      "Tendón", 
      "Ligamento", 
      "Cartílago", 
      "Arteria", 
      "Vena",
    ],
    respuestasCorrectas: ["Músculo"],
    fonetica: ["ˈmʌsəl"],
  },
  {
    id: 11,
    texto: '',
    palabra: "Cartilage",
    opciones: [
      "Cartílago", 
      "Músculo", 
      "Tendón", 
      "Ligamento", 
      "Arteria", 
      "Vena",
    ],
    respuestasCorrectas: ["Cartílago"],
    fonetica: ["ˈkɑrtələʤ"],
  },
  {
    id: 12,
    texto: '',
    palabra: "Ligament",
    opciones: [
      "Ligamento", 
      "Músculo", 
      "Tendón", 
      "Cartílago", 
      "Arteria", 
      "Vena",
    ],
    respuestasCorrectas: ["Ligamento"],
    fonetica: ["ˈlɪɡəmənt"],
  },
];